import AuthProvider from "@/context/AuthProvider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Anonomyous SMS | ts_next_js",
  description: "Generated by Asif A Owadud",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <body className={inter.className}>
          {children}
          <Toaster />

          <footer className="text-center p-4 md:p-6 bg-gray-900 text-white">
            © 2024 True Feedback. All rights reserved.
          </footer>
        </body>
      </AuthProvider>
    </html>
  );
}
